version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672" # AMQP port

  app:
    build: .
    container_name: Food-helper
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    ports:
      - "8080:8080"
    volumes:
      - .:/app
